[package]
name = "docker"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
docker-api = "0.14.0"
futures-util = "0.3.29"

[dev-dependencies]
indicatif = "0.17.7"
tokio = { version = "1.33.0", features = ["full"] }
